[versions]
agp = "8.7.3"
kotlin = "1.9.22"
coreKtx = "1.15.0"
okhttp = "4.12.0"
moshi = "1.15.0"
coroutines = "1.10.2"
applovinMax = "13.1.0"
googleAds = "23.6.0"
ironSource = "8.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
applovin-sdk = { group = "com.applovin", name = "applovin-sdk", version.ref = "applovinMax" }
google-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "googleAds" }
ironsource-sdk = { group = "com.ironsource.sdk", name = "mediationsdk", version.ref = "ironSource" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
